 "use client";
import {useRef,useState} from "react";import Link from "next/link";import {createClient} from "@/lib/supabase/client";
import {ArrowLeft,Upload,Play,Pause,Flag,Trash2} from "lucide-react";
const TYPES=["Golo","Remate","Perda de bola","Recuperação","Canto","Falta","Nota"];
export default function GameClient({game,initialEvents}:{game:any;initialEvents:any[]}){
 const supabase=createClient();const video=useRef<HTMLVideoElement>(null);const [events,setEvents]=useState(initialEvents);const [current,setCurrent]=useState(0);const [playing,setPlaying]=useState(false);const [tag,setTag]=useState("Golo");const [note,setNote]=useState("");const [uploading,setUploading]=useState(false);const [url,setUrl]=useState<string|null>(null);
 async function loadVideo(){const {data,error}=await supabase.storage.from("videos").createSignedUrl(game.video_path,3600);if(error)alert(error.message);else setUrl(data.signedUrl)}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024*1024){alert("Vídeo demasiado grande. Limite configurado: 5 GB.");return}setUploading(true);
  const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${game.user_id}/${game.id}/${Date.now()}-${safe}`;
  const {error}=await supabase.storage.from("videos").upload(path,file,{contentType:file.type,upsert:false});
  if(error)alert(error.message);else{await supabase.from("games").update({video_path:path,video_name:file.name,video_size:file.size}).eq("id",game.id);setUrl(URL.createObjectURL(file));}
  setUploading(false)
 }
 async function addEvent(){const {data,error}=await supabase.from("events").insert({game_id:game.id,user_id:game.user_id,time_seconds:current,event_type:tag,note}).select().single();if(error)alert(error.message);else{setEvents([...events,data].sort((a,b)=>a.time_seconds-b.time_seconds));setNote("")}}
 async function removeEvent(id:string){await supabase.from("events").delete().eq("id",id);setEvents(events.filter(x=>x.id!==id))}
 function seek(t:number){if(video.current){video.current.currentTime=t;video.current.play();setPlaying(true)}}
 return <main className="analysis"><header className="topbar"><Link href="/dashboard"><ArrowLeft/> Jogos</Link><div><b>{game.name}</b><span>{game.opponent||"Sem adversário"} · {game.game_date}</span></div><label className="primary upload"><Upload/> {uploading?"A enviar...":game.video_path?"Trocar vídeo":"Carregar vídeo"}<input type="file" accept="video/*" disabled={uploading} onChange={upload}/></label></header>
 <section className="analysis-body"><div className="video-panel">{url?<video ref={video} src={url} controls onTimeUpdate={e=>setCurrent(e.currentTarget.currentTime)}/>:game.video_path?<button className="video-drop" onClick={loadVideo}><Play size={48}/><h2>Abrir vídeo</h2><p>O vídeo está guardado no Supabase Storage.</p></button>:<label className="video-drop"><Upload size={48}/><h2>Carrega o vídeo do jogo</h2><p>No iPhone, escolhe um vídeo diretamente da Fototeca.</p><input type="file" accept="video/*" onChange={upload}/></label>}
 <div className="timeline"><div className="line"/>{events.map(e=><button key={e.id} title={e.event_type} style={{left:`${Math.min(98,(Number(e.time_seconds)/(video.current?.duration||300))*100)}%`}} onClick={()=>seek(Number(e.time_seconds))}/>)}</div>
 <div className="controls"><span>{format(current)}</span><button className="icon" onClick={()=>{if(video.current){video.current.paused?video.current.play():video.current.pause();setPlaying(!playing)}}}>{playing?<Pause/>:<Play/>}</button><span>{video.current?format(video.current.duration):"--:--"}</span></div></div>
 <aside className="events"><h2>Eventos</h2><div className="tag-grid">{TYPES.map(t=><button className={tag===t?"selected":""} key={t} onClick={()=>setTag(t)}>{t}</button>)}</div><div className="event-add"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Nota sobre este momento..."/><button className="primary wide" onClick={addEvent}><Flag/> Marcar em {format(current)}</button></div><div className="event-list">{events.map(e=><div className="event" key={e.id}><button onClick={()=>seek(Number(e.time_seconds))}><b>{format(Number(e.time_seconds))}</b><span><strong>{e.event_type}</strong>{e.note&&<small>{e.note}</small>}</span></button><button className="delete" onClick={()=>removeEvent(e.id)}><Trash2 size={15}/></button></div>)}</div></aside></section></main>}
function format(n:number){if(!Number.isFinite(n))return"00:00";return`${String(Math.floor(n/60)).padStart(2,"0")}:${String(Math.floor(n%60)).padStart(2,"0")}`}